export const mockSalesData = [
    {
        id: 1,
        sales_date: "2025-05-01",
        location_id: 1,
        amount: 30000,
        sales_channel: "SM",
        category: "飲料",
        tactics: "チラシ",
        employee_number: 101,
        employee_name: "田中",
        memo: "",
    },
    {
        id: 2,
        sales_date: "2025-05-01",
        location_id: 1,
        amount: 90000,
        sales_channel: "EC",
        category: "酒類",
        tactics: "エンド",
        employee_number: 102,
        employee_name: "佐藤",
        memo: "",
    },
    {
        id: 3,
        sales_date: "2025-05-02",
        location_id: 2,
        amount: 40000,
        sales_channel: "CVS",
        category: "飲料",
        tactics: "エンド",
        employee_number: 103,
        employee_name: "鈴木",
        memo: "",
    },
    {
        id: 4,
        sales_date: "2025-05-02",
        location_id: 2,
        amount: 20000,
        sales_channel: "SM",
        category: "酒類",
        tactics: "チラシ",
        employee_number: 104,
        employee_name: "高橋",
        memo: "",
    },
    {
        id: 5,
        sales_date: "2025-05-03",
        location_id: 1,
        amount: 50000,
        sales_channel: "EC",
        category: "飲料",
        tactics: "企画",
        employee_number: 105,
        employee_name: "山田",
        memo: "",
    },
    {
        id: 6,
        sales_date: "2025-05-03",
        location_id: 1,
        amount: 70000,
        sales_channel: "CVS",
        category: "酒類",
        tactics: "エンド",
        employee_number: 106,
        employee_name: "佐々木",
        memo: "",
    },
    {
        id: 7,
        sales_date: "2025-05-04",
        location_id: 2,
        amount: 60000,
        sales_channel: "SM",
        category: "飲料",
        tactics: "チラシ",
        employee_number: 107,
        employee_name: "中村",
        memo: "",
    },
    {
        id: 8,
        sales_date: "2025-05-04",
        location_id: 2,
        amount: 80000,
        sales_channel: "EC",
        category: "酒類",
        tactics: "企画",
        employee_number: 108,
        employee_name: "小林",
        memo: "",
    },
    {
        id: 9,
        sales_date: "2025-05-05",
        location_id: 1,
        amount: 100000,
        sales_channel: "CVS",
        category: "飲料",
        tactics: "エンド",
        employee_number: 109,
        employee_name: "加藤",
        memo: "",
    },
    {
        id: 10,
        sales_date: "2025-05-05",
        location_id: 1,
        amount: 120000,
        sales_channel: "SM",
        category: "酒類",
        tactics: "チラシ",
        employee_number: 110,
        employee_name: "吉田",
        memo: "",
    },
    {
        id: 11,
        sales_date: "2025-05-06",
        location_id: 2,
        amount: 110000,
        sales_channel: "EC",
        category: "飲料",
        tactics: "企画",
        employee_number: 111,
        employee_name: "山本",
        memo: "",
    },
    {
        id: 12,
        sales_date: "2025-05-06",
        location_id: 2,
        amount: 130000,
        sales_channel: "CVS",
        category: "酒類",
        tactics: "エンド",
        employee_number: 112,
        employee_name: "井上",
        memo: "",
    },

]